version: "3"

services:
  mariadb:
    image: wodby/mariadb:${MARIADB_TAG:-10.5}
    container_name: "${APP_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: $DB_DATABASE
      MYSQL_USER: $DB_USERNAME
      MYSQL_PASSWORD: $DB_PASSWORD
#    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/php:${PHP_TAG:-8.0}
    container_name: "${APP_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USERNAME
      DB_PORT: $DB_PORT
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_DATABASE
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
## Read instructions at https://wodby.com/docs/stacks/php/local/#xdebug
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_MODE: debug
#      PHP_IDE_CONFIG: serverName=my-ide
#      PHP_XDEBUG_IDEKEY: "my-ide"
#      PHP_XDEBUG_CLIENT_HOST: 172.17.0.1 # Linux
#      PHP_XDEBUG_CLIENT_HOST: host.docker.internal # Docker 18.03+ Mac/Win
#      PHP_XDEBUG_CLIENT_HOST: 10.0.75.1 # Windows
    volumes:
    - ./backend:/var/www/html
    # command: sh -c 'composer install && php artisan migrate && php artisan db:seed'

  nginx:
    image: wodby/nginx:${NGINX_TAG:-1.21}
    container_name: "${APP_NAME}_nginx"
    ports:
      - 8899:80
    depends_on:
    - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: php
      NGINX_SERVER_ROOT: /var/www/html/public
    volumes:
    - ./backend:/var/www/html

  node:
    image: wodby/node:${NODE_TAG:-16-dev}
    container_name: "${APP_NAME}_node"
    working_dir: /app
    ports:
    - 8900:5555
    volumes:
    - ./frontend:/app
    command: sh -c 'npm install && npm run dev'
